name: Build VLC AppImage

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            autoconf automake cmake build-essential \
            libtool libtool-bin pkg-config git \
            libfreetype6-dev libfribidi-dev libharfbuzz-dev \
            qt6-base-dev qt6-declarative-dev qt6-svg-dev \
            qt6-tools-dev qt6-shadertools-dev qt6-base-dev-tools \
            libxcb-keysyms1-dev libxinerama-dev libxpm-dev \
            libgnutls28-dev libarchive-dev libxml2-dev libdvbpsi-dev \
            libfaad-dev libchromaprint-dev libebur128-dev \
            libmad0-dev libmatroska-dev libmpcdec-dev libplacebo-dev \
            libsecret-1-dev libupnp-dev lua5.3 liblua5.3-dev \
            libavcodec-dev libavformat-dev libavutil-dev \
            libaom-dev libdav1d-dev libjack-jackd2-dev \
            libbluray-dev libcaca-dev libdc1394-dev \
            libdvdnav-dev libdvdread-dev libgme-dev \
            libjpeg-dev libkate-dev libass-dev \
            libmodplug-dev libmtp-dev libnfs-dev libogg-dev \
            libpng-dev libpulse-dev librsvg2-dev libsamplerate-dev \
            libshout3-dev libsoxr-dev libssh2-1-dev libtheora-dev \
            libtwolame-dev libvorbis-dev libvpx-dev \
            libraw1394-dev libavc1394-dev libsmbclient-dev libmpg123-dev libva-dev libswscale-dev libflac-dev \
            libopus-dev \
            libxkbcommon-dev lirc libvdpau-dev libx264-dev libx265-dev \
            mpg123 libprojectm-dev libzvbi-dev \
            qtbase5-dev-tools desktop-file-utils

      - name: Clone VLC
        run: |
          git clone --depth=1 https://code.videolan.org/videolan/vlc.git
          cd vlc
          ./bootstrap
          autoreconf -vf

      - name: Configure and Build VLC
        run: |
          cd vlc
          mkdir build && cd build
          export LUA_CFLAGS="$(pkg-config --cflags lua5.3)"
          export LUA_LIBS="$(pkg-config --libs lua5.3)"
          ../configure --prefix=/usr \
            --enable-alsa \
            --enable-aribb25 \
            --enable-aom \
            --enable-archive \
            --enable-aribsub \
            --enable-avahi \
            --enable-avcodec \
            --enable-avformat \
            --enable-bluray \
            --enable-caca \
            --enable-chromaprint \
            --enable-chromecast \
            --enable-dav1d \
            --enable-dc1394 \
            --disable-decklink \
            --enable-dv1394 \
            --enable-dvbpsi \
            --enable-dvdnav \
            --enable-dvdread \
            --enable-ebur128 \
            --enable-faad \
            --disable-fdkaac \
            --enable-flac \
            --disable-fluidsynth \
            --enable-fontconfig \
            --enable-freetype \
            --enable-fribidi \
            --enable-gme \
            --enable-gnutls \
            --enable-goom \
            --enable-gst-decode \
            --enable-harfbuzz \
            --enable-jack \
            --enable-jpeg \
            --enable-kate \
            --enable-kwallet \
            --enable-libass \
            --disable-libgcrypt \
            --enable-libplacebo \
            --enable-libva \
            --enable-libxml2 \
            --enable-lirc \
            --enable-mad \
            --enable-matroska \
            --enable-microdns \
            --enable-mod \
            --enable-mpc \
            --enable-mpg123 \
            --enable-mtp \
            --enable-ncurses \
            --enable-nfs \
            --enable-nls \
            --enable-notify \
            --enable-ogg \
            --enable-oggspots \
            --disable-opencv \
            --enable-opus \
            --enable-png \
            --enable-postproc \
            --enable-projectm \
            --enable-pulse \
            --enable-qt \
            --enable-qtdeclarative \
            --enable-qtshadertools \
            --enable-qtsvg \
            --enable-qtwayland \
            --disable-rist \
            --disable-rpath \
            --enable-samplerate \
            --disable-schroedinger \
            --enable-secret \
            --enable-sftp \
            --enable-shout \
            --enable-skins2 \
            --enable-smbclient \
            --enable-soxr \
            --enable-speex \
            --enable-srt \
            --enable-svg \
            --enable-svgdec \
            --enable-taglib \
            --enable-twolame \
            --disable-update-check \
            --enable-upnp \
            --enable-vcd \
            --enable-vdpau \
            --enable-vlc \
            --enable-vorbis \
            --enable-vpx \
            --enable-wayland \
            --enable-x264 \
            --enable-x265 \
            --enable-zvbi
          make -j$(nproc)

      - name: Install into AppDir
        run: |
          cd vlc/build
          make DESTDIR=$GITHUB_WORKSPACE/AppDir install
          cp ../vlc.desktop $GITHUB_WORKSPACE/AppDir/usr/share/applications/
          cp ../share/icons/128x128/vlc.png $GITHUB_WORKSPACE/AppDir/usr/share/icons/hicolor/128x128/apps/vlc.png

      - name: Download linuxdeploy and AppImage plugin
        run: |
          wget -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          ./linuxdeploy-x86_64.AppImage --appdir AppDir \
            -d AppDir/usr/share/applications/vlc.desktop \
            -i AppDir/usr/share/icons/hicolor/128x128/apps/vlc.png \
            --output appimage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vlc-appimage
          path: ./*.AppImage
