name: Build VLC Git Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Distrobox and Podman
        run: |
          sudo apt update
          sudo apt install -y podman curl
          curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo bash

      - name: Create and enter Arch container
        run: |
          distrobox create --name arch-build --image archlinux:latest --yes
          distrobox enter arch-build -- bash -c '
            set -eux

            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel git wget sudo

            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

            su builder <<EOF
              set -eux
              cd ~
              mkdir vlc-git && cd vlc-git
              wget https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=vlc-git -O PKGBUILD
              makepkg -s --noconfirm
              cp vlc-git-*.pkg.tar.zst /tmp/
            EOF
          '

      - name: Copy package from container
        run: |
          mkdir artifacts
          distrobox enter arch-build -- bash -c 'cat /tmp/vlc-git-*.pkg.tar.zst' > artifacts/vlc-git.pkg.tar.zst

      - name: Upload .pkg.tar.zst
        uses: actions/upload-artifact@v4
        with:
          name: vlc-git-pkg
          path: artifacts/vlc-git.pkg.tar.zst
