name: Build VLC AppImage

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install distrobox and podman
        run: |
          sudo apt update
          sudo apt install -y podman curl git wget

          curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo bash

      - name: Create Arch container and build VLC
        run: |
          distrobox create --name arch-vlc --image archlinux:latest --yes
          
          distrobox enter arch-vlc -- bash -c '
            set -e

            pacman -Syu --noconfirm
            pacman -S --needed --noconfirm base-devel git wget sudo

            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            su builder <<EOF
              mkdir vlc-git && cd vlc-git
              wget https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=vlc-git -O PKGBUILD
              makepkg -s --noconfirm
              mkdir -p /tmp/AppDir/usr
              cp -r /usr/bin/vlc /tmp/AppDir/usr/bin/
              cp -r /usr/share/applications/vlc.desktop /tmp/AppDir/usr/share/applications/
              cp -r /usr/share/icons/hicolor/128x128/apps/vlc.png /tmp/AppDir/usr/share/icons/hicolor/128x128/apps/
            EOF
          '

      - name: Download linuxdeploy
        run: |
          wget -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Create AppImage
        run: |
          mkdir -p AppDir
          sudo cp -r /var/lib/containers/storage/overlay*/diff/tmp/AppDir/* AppDir/ || true
          ./linuxdeploy-x86_64.AppImage --appdir AppDir \
            -d AppDir/usr/share/applications/vlc.desktop \
            -i AppDir/usr/share/icons/hicolor/128x128/apps/vlc.png \
            --output appimage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vlc-appimage
          path: ./*.AppImage
